### ISSUE TITLE
error: type "subscription_status" does not exist

### ISSUE THREAD

**Issue by girishvisaero** [webprodigies/webprodigies-cypress#5]
at /Users/girishchaudhari/girish_workspace/webprodigies-cypress/node_modules/drizzle-kit/bin.cjs:24462:21
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PgPostgres.query (/Users/girishchaudhari/girish_workspace/webprodigies-cypress/node_modules/drizzle-kit/bin.cjs:25423:21)
    at async Command.<anonymous> (/Users/girishchaudhari/girish_workspace/webprodigies-cypress/node_modules/drizzle-kit/bin.cjs:63261:9)

**Comment by girishvisaero** [comment]
<img width="1470" alt="Screenshot 2024-02-23 at 7 09 08 PM" src="https://github.com/webprodigies/webprodigies-cypress/assets/119156991/9fb6c7c8-bd53-432d-9234-5b4a6c1cf73d">
how can I fix this issue? wanna try this saas based product.

**Comment by zbango** [comment]
Having the same issue. Any ideas?

**Comment by girishvisaero** [comment]
Not yet
